import { COMPANY } from '@/lib/company'
import { CONSULTATION_PLATFORM_FEE, DIAGNOSTIC_PLATFORM_FEE } from '@/lib/pricing'

// The Terms & Conditions and the Privacy Policy, shown at /terms-of-use and /privacy-policy to visitors and to
// signed-in patients, doctors, hospitals, diagnostic centres and staff alike. A paragraph is a string (with **bold**
// allowed); a bulleted list is an array of strings. When either changes, update LEGAL_UPDATED.

export const LEGAL_UPDATED = '8 October 2026'
export const LEGAL_ENTITY = 'Zebrold International Holdings Pvt Ltd'

export type LegalSection = { id: string; title: string; body: (string | string[])[] }
export type LegalDocument = { title: string; summary: string[]; sections: LegalSection[] }

const contactLines = [
  `**${LEGAL_ENTITY}**, operating Consult Your Doctor`,
  `Address: ${COMPANY.address}`,
  `Email: ${COMPANY.email}`,
  `Phone: ${COMPANY.phone}`,
]

export const TERMS: LegalDocument = {
  title: 'Terms & Conditions',
  summary: [
    'Consult Your Doctor is a healthcare technology platform connecting you with independent licensed doctors, hospitals, and certified diagnostic laboratories. They provide your clinical care; we provide booking, secure payment processing, digital records, and care coordination.',
    'We are NOT an emergency response service. If you are experiencing a medical emergency, chest pain, severe trauma, or acute breathing distress, immediately call 112 or visit the nearest hospital emergency room.',
    `When you book online, you pay the doctor’s consultation fee or lab test price plus a transparent platform service fee (₹${CONSULTATION_PLATFORM_FEE} for doctor consultations, ₹${DIAGNOSTIC_PLATFORM_FEE} for diagnostic laboratory tests). Desk payments at hospital or lab reception can be settled via UPI QR code or cash without online platform fees.`,
    'Zebrold AI provides conversational platform navigation, slot discovery, and adherence follow-up reminders, but it is not a doctor. All clinical decisions, diagnoses, and prescriptions are made solely by licensed medical practitioners.',
    'Cancellations made at least 2 hours prior to your scheduled consultation or sample collection qualify for a full refund, processed back to your original payment method within 5 to 7 business days.',
  ],
  sections: [
    {
      id: 'about',
      title: '1. About These Terms',
      body: [
        `These Terms & Conditions (“Terms”) govern your access to and use of Consult Your Doctor (the “Platform”), accessible via consultyourdoctor.de, our mobile web applications, and our dedicated portals for patients, doctors, hospitals, diagnostic centres, and administrative staff. The Platform is owned and operated by ${LEGAL_ENTITY} (“Company”, “we”, “us”, or “our”).`,
        'By creating an account, signing in, scheduling an appointment, ordering diagnostic tests, or otherwise using the Platform, you enter into a legally binding agreement and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you must not use or access the Platform.',
      ],
    },
    {
      id: 'service',
      title: '2. Nature of Platform & Medical Disclaimers',
      body: [
        'Consult Your Doctor operates strictly as a digital technology intermediary and healthcare communication platform. We facilitate discovery, appointment scheduling, teleconsultation communication, hospital bed coordination, diagnostic test ordering, fee collection, and digital health records management.',
        [
          '**Independent Healthcare Providers:** All doctors, hospitals, clinics, and diagnostic centres listed on the Platform (“Healthcare Partners”) are independent third-party professional providers. They are solely responsible for the medical care, clinical advice, diagnoses, treatment plans, prescriptions, sample analyses, and lab reports they issue. We do not practice medicine, operate medical clinics, or supervise clinicians in their professional judgment.',
          '**No Doctor-Patient Relationship with the Platform:** The use of our technology does not create a doctor-patient relationship between you and Consult Your Doctor. The doctor-patient relationship exists strictly between you and your chosen healthcare professional.',
          '**NOT for Medical Emergencies:** The Platform is NOT designed or equipped for emergency medical care. If you experience severe chest pain, shortness of breath, sudden numbness, uncontrolled bleeding, poisoning, suicidal ideation, or any life-threatening situation, call India’s national emergency number 112 immediately or proceed to the nearest emergency casualty ward.',
          '**General Health Information:** Health articles, educational resources, and answers generated by Zebrold AI are for general informational purposes only and do not constitute clinical medical advice. Always consult a qualified medical doctor for any health questions.',
        ],
      ],
    },
    {
      id: 'accounts',
      title: '3. User Accounts, Eligibility & Responsibilities',
      body: [
        [
          '**Age & Legal Capacity:** You must be at least 18 years of age and possess the legal capacity to form a binding contract. If you are booking care for a minor (under 18) or a dependent family member, you represent that you are their parent or legal guardian and have lawful authority to share their health details and make healthcare decisions on their behalf.',
          '**Authentication & Security:** Patients sign in securely using their mobile number and a time-sensitive One-Time Password (OTP). Partner doctors, hospitals, and diagnostic staff sign in with registered credentials; any temporary passwords issued must be reset upon initial sign-in. You are responsible for safeguarding your login credentials and devices.',
          '**Accuracy of Medical Information:** You must provide accurate, current, and complete health data, including known drug allergies, active medications, pregnancy status, pre-existing conditions, and past surgeries. Concealing or misrepresenting health information can severely compromise clinical care.',
          '**Account Confidentiality:** You must notify us immediately at ' + COMPANY.email + ' if you suspect unauthorized access or any security breach involving your account.',
        ],
      ],
    },
    {
      id: 'bookings',
      title: '4. Consultations, Bookings & Payment Terms',
      body: [
        [
          `**Doctor Consultations:** When booking a consultation online, you pay the practitioner’s consultation fee plus a platform service fee of ₹${CONSULTATION_PLATFORM_FEE}. Consultations may be conducted in person at the doctor’s hospital/clinic or via teleconsultation where offered.`,
          `**Diagnostic Lab Tests:** When booking lab tests online, you pay the diagnostic centre’s published price for each test plus a platform service fee of ₹${DIAGNOSTIC_PLATFORM_FEE}. Full test pricing is transparently displayed before payment confirmation.`,
          '**Payment Processing:** Online payments are processed through our authorized payment gateway partner, PayU. All online transactions are encrypted via industry-standard protocols. We do not store credit/debit card numbers or netbanking credentials on our servers.',
          '**Front-Desk Payments:** When registering or checking in directly at a partner hospital or diagnostic centre front desk, patients may settle charges directly with the facility via UPI (scanning the facility’s QR code) or cash. Desk payments do not incur the online platform service fee.',
          '**Booking Confirmation:** A booking is officially confirmed once the payment is captured or a front-desk admission is finalized. Unpaid online reservations may be released after a hold period to keep appointment slots open for other patients.',
          '**Taxes:** All stated consultation and test fees are inclusive of applicable taxes unless explicitly indicated otherwise.',
        ],
      ],
    },
    {
      id: 'cancellations',
      title: '5. Cancellations, Rescheduling & Refund Policy',
      body: [
        [
          '**Patient Cancellations:** You may cancel or reschedule a scheduled appointment or lab booking free of charge up to 2 hours prior to the scheduled slot time through your patient portal account or by reaching out to our support team.',
          '**Provider Cancellations & No-Shows:** If a doctor, hospital, or diagnostic centre cancels an appointment, encounters an unexpected emergency, or fails to attend your scheduled session, you will be offered an immediate reschedule or an automatic 100% refund, including all platform service fees.',
          '**Non-Refundable Services:** Once a consultation has commenced or been completed, or once a biological sample has been collected for laboratory testing, the associated fees become non-refundable.',
          '**Patient Missed Appointments (No-Shows):** If you fail to arrive for an in-person appointment or fail to join a teleconsultation without cancelling at least 2 hours in advance, the healthcare provider reserves the right to mark the booking as completed or forfeited without refund.',
          '**Refund Settlement Timeline:** Approved refunds are initiated immediately to the original source payment method (card, UPI, or netbanking). Banking networks and payment gateways typically credit the funds to your account within 5 to 7 business days.',
        ],
      ],
    },
    {
      id: 'records',
      title: '6. Prescriptions, Health Records & Barcode Verification',
      body: [
        [
          '**Prescription Validity & Authentication:** Prescriptions generated through the Platform are written, reviewed, and authorized exclusively by the attending registered medical practitioner. Each digital prescription carries a unique prescription identification code and a scannable verification barcode for pharmacist validation.',
          '**30-Day Standard Validity:** Unless the prescribing clinician explicitly specifies an alternate duration on the prescription document, a prescription is legally valid for a maximum period of 30 days from its date of issuance. Prescription refills require a follow-up consultation unless ongoing refills are explicitly authorized.',
          '**Restricted & Schedule X Medications:** Clinicians on the Platform adhere strictly to the National Medical Commission (NMC) Telemedicine Practice Guidelines. Specific habit-forming, narcotic, and Schedule X pharmaceuticals cannot and will not be prescribed via teleconsultation.',
          '**Diagnostic Laboratory Reports:** Diagnostic reports are analyzed, generated, and electronically certified by the respective partner diagnostic laboratory. Diagnostic results must be interpreted by your treating physician in conjunction with your clinical history.',
          '**Secure Health Document Access:** Medical records, prescriptions, and lab test reports are stored with end-to-end access controls. Download links generated in your profile are time-limited signed URLs that expire automatically to protect your privacy.',
        ],
      ],
    },
    {
      id: 'inpatients',
      title: '7. Inpatient Admissions & Hospital Bed Management',
      body: [
        [
          '**Bed Allocation:** The Platform facilitates hospital bed tracking and inpatient reservations (such as General Ward, Semi-Private, Deluxe Private, and ICU). Bed availability shown on the Platform reflects data provided by partner hospitals.',
          '**Hospital Clinical Responsibility:** The partner hospital is solely responsible for clinical admissions, bedside nursing, surgical procedures, medication administration, and patient safety throughout any inpatient stay.',
          '**Admission Documentation & Welcome Letters:** Patients admitted to partner hospitals receive an official digital Admission Welcome Letter outlining admission date, treating consultant, allocated ward/bed number, and hospital emergency contact details.',
          '**Inpatient Billing & Discharge:** Daily bed charges, procedure fees, and ancillary medical services incurred during a hospital admission are billed and settled directly with the hospital according to their published tariff and insurance arrangements.',
        ],
      ],
    },
    {
      id: 'ai',
      title: '8. Zebrold AI Health Assistant & Follow-Up Services',
      body: [
        'Zebrold AI is our proprietary intelligent health assistant integrated throughout the Platform. It provides multilingual guidance, helps patients search for medical specialists and lab tests, answers general questions about Platform features, and coordinates post-consultation follow-up.',
        [
          '**NOT a Licensed Physician:** Zebrold AI is an assistive algorithmic technology. It cannot formulate a medical diagnosis, prescribe drugs, or alter clinical treatment regimens. Every medical recommendation or prescription is issued solely by a human registered medical practitioner.',
          '**Prescription Safety Checks:** Where AI tools assist clinicians by scanning draft prescriptions for potential dosage abnormalities, duplicate medications, or known drug-allergy interactions, these automated alerts are advisory only. The prescribing doctor retains complete discretion and final responsibility.',
          '**Automated Follow-Up & Adherence:** With your consent, Zebrold AI may send automated follow-up messages via WhatsApp, SMS, or email to remind you of prescribed medication schedules and enquire about your recovery progress.',
          '**Worsening Symptoms:** If you report deteriorating health conditions or red-flag symptoms to Zebrold AI, the system will urge you to contact your treating doctor immediately or call 112.',
        ],
      ],
    },
    {
      id: 'reviews',
      title: '9. Patient Ratings & Authentic Reviews',
      body: [
        [
          '**Verified Patient Feedback:** Only patients who have completed a booked consultation or diagnostic test through the Platform are permitted to submit ratings and written reviews.',
          '**Privacy Protection:** To protect patient confidentiality, published reviews display only your first name and the initial of your last name (for example, "Rahul S."). Sensitive health details should never be included in reviews.',
          '**Authenticity & Moderation:** We do not compensate reviewers, manipulate ratings, or artificially boost provider profiles. We reserve the right to remove reviews that contain abusive language, hate speech, false statements, defamation, or private medical details.',
        ],
      ],
    },
    {
      id: 'partners',
      title: '10. Partner Healthcare Obligations (Doctors, Hospitals & Labs)',
      body: [
        'Healthcare practitioners, hospital administrators, diagnostic laboratory operators, and clinical staff utilizing our partner portals agree to:',
        [
          'Maintain active, unrestricted professional registrations with the National Medical Commission (NMC), State Medical Councils, or accredited regulatory authorities, and immediately notify us of any suspension or inquiry;',
          'Exercise independent professional medical judgment and uphold the highest clinical standards of care for every patient consultation;',
          'Ensure all doctor credentials, qualifications, consultation fees, lab test menus, bed availability, and operational hours displayed on the Platform are truthful, accurate, and kept up to date;',
          'Strictly protect patient health information under the Digital Personal Data Protection Act, 2023 (DPDP Act) and applicable medical council regulations, accessing patient records strictly on a clinical need-to-know basis;',
          'Accurately record and reconcile all front-desk transactions (cash and UPI payments) collected on site, and honor all confirmed appointment slots;',
          'Safeguard staff portal credentials and immediately report any suspected credential compromise or unauthorized access to our security team.',
        ],
      ],
    },
    {
      id: 'use',
      title: '11. Acceptable Use Policy',
      body: [
        'When accessing or using the Platform, you agree not to:',
        [
          'Use the Platform for any unlawful, deceptive, fraudulent, or harmful purpose;',
          'Impersonate any person or entity, falsify patient identity, or book consultations using stolen payment information;',
          'Access or attempt to access medical records, patient databases, or portal areas for which you have not been granted explicit authorization;',
          'Probe, scan, reverse engineer, decompile, or test the vulnerability of the Platform or breach its security measures;',
          'Scrape, crawl, harvest, or index physician profiles, test rates, hospital listings, or platform content using automated scripts or bots;',
          'Upload or transmit malicious code, malware, viruses, or disruptive files.',
        ],
        'Violations of this Acceptable Use Policy may result in immediate account termination, revocation of portal credentials, and referral to law enforcement authorities.',
      ],
    },
    {
      id: 'ip',
      title: '12. Intellectual Property Rights',
      body: [
        `All rights, title, and interest in and to the Platform—including but not limited to software code, algorithms, interface designs, trademarks, the “Consult Your Doctor” and “Zebrold” brand names and logos, clinical PDF formatting templates, and curated content—belong exclusively to ${LEGAL_ENTITY} or its licensors.`,
        'You are granted a limited, personal, non-exclusive, non-transferable, revocable license to access and use the Platform strictly for personal healthcare management or authorized professional care delivery in accordance with these Terms.',
      ],
    },
    {
      id: 'liability',
      title: '13. Limitation of Liability & Indemnification',
      body: [
        [
          '**Platform Availability:** While we strive to maintain uninterrupted service availability, we do not warrant that the Platform will always be error-free, uninterrupted, or free from temporary technical disruptions.',
          '**Clinical Disclaimer:** Consult Your Doctor is an intermediary platform and is NOT liable for any medical negligence, misdiagnosis, treatment error, surgical outcome, delayed lab report, or clinical omission attributable to any independent doctor, hospital, or diagnostic laboratory.',
          '**Monetary Cap:** To the maximum extent permitted by applicable law, our aggregate liability for any claims arising out of or related to your use of the Platform shall be strictly capped at the total amount in platform service fees actually paid by you to Consult Your Doctor in the 12 months preceding the event giving rise to liability.',
          '**Consumer Rights:** Nothing in these Terms shall limit or exclude any statutory rights that cannot be waived under Indian consumer protection laws.',
        ],
      ],
    },
    {
      id: 'privacy',
      title: '14. Data Privacy & Personal Health Information',
      body: [
        'Your privacy and the security of your health data are of paramount importance. Our collection, processing, encryption, and sharing of personal data and medical records are governed by our Privacy Policy, which is incorporated into and forms an integral part of these Terms.',
      ],
    },
    {
      id: 'changes',
      title: '15. Modifications to Terms',
      body: [
        'We may revise and update these Terms periodically to reflect changes in our services, technological upgrades, regulatory requirements, or legal standards. The “Last Updated” date at the top of this document indicates the effective date of the latest version. For material modifications, we will provide prominent notice through the Platform or via registered email. Continued use of the Platform following updated Terms constitutes your acceptance.',
      ],
    },
    {
      id: 'law',
      title: '16. Governing Law & Dispute Resolution',
      body: [
        'These Terms and any dispute or claim arising out of or in connection with them shall be governed by and construed in accordance with the laws of India. Any legal suit, action, or proceeding arising out of or related to these Terms shall be instituted exclusively in the competent courts located in India.',
      ],
    },
    {
      id: 'contact',
      title: '17. Contact Us & Grievance Redressal',
      body: [
        contactLines,
        `**Grievance Officer:** In accordance with the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023, you may address grievances to our designated Grievance Officer:`,
        [
          `Attention: Grievance Officer, ${LEGAL_ENTITY}`,
          `Email: ${COMPANY.email} (with subject line: “Grievance Redressal”)`,
          `Phone: ${COMPANY.phone}`,
          'Response Timeline: All grievances will be acknowledged within 48 hours of receipt and addressed within 30 days.',
        ],
      ],
    },
  ],
}

export const PRIVACY: LegalDocument = {
  title: 'Privacy Policy',
  summary: [
    'We collect the details needed to book and deliver your care: who you are, how to reach you, your health information and your bookings and payments.',
    'Your health information is shared only with the doctors, hospitals and diagnostic centres you book, and with the service providers that run the platform for us. We never sell it.',
    'Medical files are stored privately and opened only through short-lived secure links.',
    'You can see, correct and download your information, and ask us to delete it, subject to the law on keeping medical records.',
  ],
  sections: [
    {
      id: 'who',
      title: '1. Who we are',
      body: [
        `Consult Your Doctor is operated by ${LEGAL_ENTITY} (“we”, “us”). We decide how and why your personal information is used on the platform and are responsible for it (as the “data fiduciary” under India’s Digital Personal Data Protection Act, 2023, and the “controller” under the EU GDPR where it applies).`,
        'Doctors, hospitals and diagnostic centres are also responsible for the medical records they create about you, under the rules that apply to their profession.',
      ],
    },
    {
      id: 'collect',
      title: '2. The information we collect',
      body: [
        [
          '**Account details:** your name, mobile number, email address, and for partners and staff, a login ID and password (stored only in encrypted form).',
          '**Profile details you add:** date of birth, sex, blood group, address and emergency contact, and the same for family members you book for.',
          '**Health information:** symptoms and complaints, vitals (such as blood pressure, pulse, oxygen, temperature, weight, height and BMI), prescriptions, diagnoses, lab test results and reports, documents you or your providers upload, hospital admission and bed details, and allergies.',
          '**Bookings and payments:** who you booked, when and where, the amount, the payment method and the transaction reference. Card and bank details are handled by our payment partner PayU; we do not receive or store them.',
          '**Reviews** you write about doctors.',
          '**Messages:** what you type to Zebrold AI and support requests you send us.',
          '**Technical information:** the cookies that keep you signed in, your browser type and IP address in our logs, and preferences saved in your browser (such as your chosen language and unsent prescription drafts for doctors).',
          '**For partners:** professional details such as qualifications, registration number, specialty, education, fees, facilities, test prices, insurance accepted, signature images for prescriptions, and the details of staff who use the portal.',
        ],
      ],
    },
    {
      id: 'use',
      title: '3. How we use it',
      body: [
        [
          'to create and secure your account and sign you in (including sending one-time codes);',
          'to show you doctors, labs, prices and available times, and to make, confirm and manage your bookings;',
          'to share your details and health information with the doctor, hospital or diagnostic centre you book, so they can care for you;',
          'to take payments, issue receipts and process refunds;',
          'to deliver prescriptions, lab reports and health updates to your account, and to send them to you by WhatsApp and email;',
          'to answer your questions through Zebrold AI and our support team, and, where offered, to follow up with you after a consultation;',
          'to show your reviews on doctors’ profiles and our home page (first name and last-name initial only);',
          'to keep the platform safe, prevent fraud and misuse, and fix problems;',
          'to meet our legal obligations, such as keeping medical and financial records and responding to lawful requests.',
        ],
        'We use your information on the basis of your consent (which you give when you sign up, book or upload information, and can withdraw), to perform the services you ask for, to comply with the law, and for our legitimate interest in running a safe and reliable platform. We do not use your health information for advertising, and we do not sell your personal information.',
      ],
    },
    {
      id: 'share',
      title: '4. Who we share it with',
      body: [
        [
          '**The providers you book:** the doctor, hospital or diagnostic centre sees the details and health information they need for your care. Your treating doctor can see records added at the hospital for your visit, including any admission.',
          '**Service providers who run the platform for us,** under contracts that require them to protect your information and use it only on our instructions: Supabase (database, sign-in and secure file storage), PayU (payments), Meta (WhatsApp messages), our email provider, Cloudflare (Zebrold AI answers; it does not use what it is sent to train its models), and our hosting provider.',
          '**Authorities,** when the law requires it, or to protect someone’s life or safety in an emergency.',
          '**A buyer or successor,** if our business is reorganised or sold, under the same protections.',
        ],
      ],
    },
    {
      id: 'security',
      title: '5. How we protect it',
      body: [
        [
          'All connections to the platform are encrypted (HTTPS).',
          'Prescriptions, reports and health documents are kept in private storage and opened only through secure links that expire after a short time.',
          'Each portal can see only what it needs: patients see their own records, doctors see their own patients, and hospitals and diagnostic centres see their own bookings.',
          'Staff access is limited, logged by our providers, and protected by passwords and one-time codes.',
        ],
        'No system is perfectly secure. If a breach affects your information, we will tell you and the authorities as the law requires.',
      ],
    },
    {
      id: 'retention',
      title: '6. How long we keep it',
      body: [
        'We keep your account information while your account is open. Medical records (prescriptions, reports and health records) and payment records are kept for as long as the law requires providers and businesses to keep them, even after you close your account. When we no longer need information, we delete or anonymise it.',
      ],
    },
    {
      id: 'rights',
      title: '7. Your rights and choices',
      body: [
        [
          'see the information we hold about you, and download your prescriptions and reports from your account;',
          'correct or update your details (most can be changed in your profile);',
          'ask us to delete your information, subject to the records we must keep by law;',
          'withdraw your consent at any time (this does not affect what was done before, and some services cannot work without it);',
          'nominate someone to exercise your rights if you die or are unable to;',
          'complain to us, to our Grievance Officer, and to the Data Protection Board of India (or, in the EU, to your data protection authority).',
        ],
        `To use any of these rights, write to ${COMPANY.email} from the email address or mobile number on your account, or use Help & Support in your account. We may need to confirm your identity first.`,
      ],
    },
    {
      id: 'children',
      title: '8. Children',
      body: [
        'Accounts are for adults. Information about a child under 18 is provided and managed by their parent or legal guardian, who consents on the child’s behalf. We do not track children or show them targeted advertising.',
      ],
    },
    {
      id: 'cookies',
      title: '9. Cookies and browser storage',
      body: [
        'We use only the cookies the platform needs to work: to keep you signed in securely and to send you to the right portal. We also save a few preferences in your browser, such as your Zebrold AI language, your recent AI conversation for that browser session, and unsent prescription drafts for doctors. We do not use advertising cookies.',
      ],
    },
    {
      id: 'transfers',
      title: '10. Where your information is processed',
      body: [
        'Some of our service providers, and our office in Germany, may process information outside India. When that happens, we use providers that protect it to the standards required by Indian law and, where it applies, the GDPR.',
      ],
    },
    {
      id: 'changes',
      title: '11. Changes to this policy',
      body: ['We will update this policy when how we handle information changes. The date at the top shows the latest version, and we will tell you about important changes in the app or by email.'],
    },
    {
      id: 'contact',
      title: '12. Contact us and our Grievance Officer',
      body: [contactLines, `Grievance Officer: ${COMPANY.email} (subject line “Grievance”). We acknowledge complaints within 48 hours and aim to resolve them within 30 days.`],
    },
  ],
}
